version: "3.8"

services:
  api1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - PORT=8001
  api2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - PORT=8002
  api3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - PORT=8003
